import "./globals.css";
import "./themes.css"
import TopBar from "@/components/TopBar";
import SideBar from "@/components/SideBar";
import BottomBar from "@/components/BottomBar";
import ExplorerBar from "@/components/ExplorerBar";



export const metadata = {
  title: "Renzo Cervantes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="TopBar">
            <TopBar />
          </div>
          <div className="SideBar">
            <SideBar />
          </div>
          <div className="BottomBar">
            <BottomBar />
          </div>
          <div className="Window">
            <ExplorerBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
